[workspace]
resolver = "2"
members = [
    "kernel",
    "sel4_common",
    "sel4_cspace",
    "sel4_ipc",
    "sel4_task",
    "sel4_vspace",
    "serial-frame",
    "serial-impl/pl011",
    "serial-impl/sbi",
    "rel4-arch",
    "rel4-utils",
]

default-members = [
    "kernel",
    "sel4_common",
    "sel4_cspace",
    "sel4_ipc",
    "sel4_task",
    "sel4_vspace",
    "serial-frame",
    "serial-impl/pl011",
    "serial-impl/sbi",
    "rel4-arch",
    "rel4-utils",
]

exclude = ["rel4_config", "xtask", "dv", "tools/verus", "tools/verus-analyzer"]

[profile.release]
lto = true

[workspace.dependencies]
aarch64-cpu = "9.4.0"
rel4-utils = { path = "rel4-utils" }
rel4-arch = { path = "rel4-arch" }

[workspace.metadata.sel4_cspace]
features = ["verify"]
build_features = ["verus"]
verify_features = ["verify"]

[patch.'https://github.com/reL4team2/serial-frame.git']
serial-frame = { path = "serial-frame" }
[patch.'https://github.com/reL4team2/serial-impl-pl011.git']
serial-impl-pl011 = { path = "serial-impl/pl011" }
[patch.'https://github.com/reL4team2/serial-impl-sbi.git']
serial-impl-sbi = { path = "serial-impl/sbi" }
[patch.'https://github.com/reL4team2/sel4_common.git']
sel4_common = { path = "sel4_common" }
[patch.'https://github.com/reL4team2/sel4_cspace.git']
sel4_cspace = { path = "sel4_cspace" }
[patch.'https://github.com/reL4team2/sel4_ipc.git']
sel4_ipc = { path = "sel4_ipc" }
[patch.'https://github.com/reL4team2/sel4_task.git']
sel4_task = { path = "sel4_task" }
[patch.'https://github.com/reL4team2/sel4_vspace.git']
sel4_vspace = { path = "sel4_vspace" }
